name: AI Java Code Fixer

on:
  push:
    branches:
      - main

jobs:
  analyze-and-fix-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Prepare AI Request
        run: |
          echo '{
            "model": "code-davinci-003",
            "prompt": "Analyze and fix the following Java code:\\n\\n$(cat src/Main.java)",
            "max_tokens": 2000,
            "temperature": 0.2
          }' > request.json

      - name: Send Code to AI
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d @request.json \
            https://api.openai.com/v1/completions > response.json

      - name: Apply Fixes
        run: |
          python3 -c "
import json
with open('response.json', 'r') as f:
    response = json.load(f)
fixed_code = response['choices'][0]['text'].strip()
with open('src/Main.java', 'w') as f:
    f.write(fixed_code)
print('Code fixes applied successfully.')
          "

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "AI fixed Java code issues" || echo "No changes to commit."
          git push
