name: Fix Java Compilation Issues with OpenAI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  fix-java-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Prepare OpenAI Request
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Read the source code and escape it for JSON
          SOURCE_CODE=$(cat src/Main.java | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | tr '\n' ' ')
          
          # Create the JSON payload file manually
          cat > request.json << EOF
          {
            "model": "gpt-3.5-turbo",
            "messages": [
              {
                "role": "system", 
                "content": "You are a Java code fixing assistant. Analyze the provided code and suggest a fix for any compilation issues."
              },
              {
                "role": "user", 
                "content": "Please fix the compilation errors in this Java source code. Provide the complete corrected source code:\n\n${SOURCE_CODE}"
              }
            ],
            "max_tokens": 300,
            "temperature": 0.5
          }
          EOF

          # Send the request using the manually created JSON file
          curl -v -X POST https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d @request.json > response.json
      
      - name: Process OpenAI Response
        run: |
          # Extract the fixed code
          jq -r '.choices[0].message.content' response.json | sed 's/```java//g' | sed 's/```//g' > src/Main.java
      
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Fix Java compilation issues using OpenAI"
          git push
