name: Fix Java Compilation Issues with OpenAI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fix-java-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'   # או את הגירסה המתאימה

      - name: Run the code linter
        run: |
          javac Main.java || echo "Compilation failed. Passing to OpenAI..."

      - name: Use OpenAI API to fix code
        id: fix_code
        run: |
          curl -X POST https://api.openai.com/v1/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d '{
              "model": "gpt-4",
              "prompt": "Fix the compilation error in this Java code:\n\n'"$(cat Main.java)"'\n\nPlease add appropriate data types to the method parameters.",
              "max_tokens": 150,
              "temperature": 0.5
            }' > response.json

      - name: Update code with fixed version
        run: |
          FIXED_CODE=$(cat response.json | jq -r '.choices[0].text')
          echo "$FIXED_CODE" > Main.java

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Main.java
          git commit -m "Fix Java compilation issues using OpenAI"
          git push
