name: Fix Java Compilation Issues with OpenAI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  fix-java-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Run the code linter and prepare error message
        id: compile_check
        continue-on-error: true
        run: |
          if ! javac src/Main.java; then
            ERROR_MESSAGE=$(javac src/Main.java 2>&1)
            echo "error_message<<EOF" >> $GITHUB_OUTPUT
            echo "$ERROR_MESSAGE" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            exit 1
          fi
      
      - name: Use OpenAI API to fix code
        if: steps.compile_check.outcome == 'failure'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ERROR_MESSAGE: ${{ steps.compile_check.outputs.error_message }}
        run: |
          # Read the original source code
          SOURCE_CODE=$(cat src/Main.java | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
          
          # Prepare the JSON payload
          JSON_PAYLOAD=$(jq -n \
            --arg model "gpt-3.5-turbo" \
            --arg source "$SOURCE_CODE" \
            --arg error "$ERROR_MESSAGE" \
            '{
              "model": $model,
              "messages": [
                {"role": "system", "content": "You are a helpful Java code fixing assistant."},
                {"role": "user", "content": "Fix the following Java compilation error:\n\nError Message:\n'"$error"'\n\nOriginal Source Code:\n'"$SOURCE_CODE"'\n\nPlease provide the full corrected source code."}
              ],
              "max_tokens": 500,
              "temperature": 0.5
            }')
          
          # Send the request
          curl -X POST https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d "$JSON_PAYLOAD" > response.json
      
      - name: Extract and Update Fixed Code
        if: steps.compile_check.outcome == 'failure'
        run: |
          # Extract the fixed code from the response
          FIXED_CODE=$(jq -r '.choices[0].message.content' response.json | sed 's/```java//g' | sed 's/```//g')
          echo "$FIXED_CODE" > src/Main.java
      
      - name: Commit and push changes
        if: steps.compile_check.outcome == 'failure'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/Main.java
          git commit -m "Fix Java compilation issues using OpenAI"
          git push
