      
      - name: Verify Fixed Code
        run: |
          # Attempt to compile the fixed code
          if ! javac src/Main.java; then
            echo "Compilation failed after AI fix"
            exit 1
          fi
      
      - name: Commit Changes
        if: github.event_name == 'push'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Fix Java compilation issues using OpenAI"
          git push

  verify-pull-request:
    needs: fix-java-issue
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Compile Java Code
        run: |
          # Attempt to compile the code to ensure it works
          if ! javac src/Main.java; then
            echo "Compilation failed"
            exit 1
          fi

      - name: Comment on PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Java code successfully compiled." > comment.txt
          gh pr comment ${{ github.event.pull_request.number }} --body-file comment.txt
