name: Analyze and Fix Java Issues Automatically
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  analyze-and-fix:
    runs-on: ubuntu-latest
    steps:
      # שלב 1: שליפת הקוד מה-repository
      - name: Checkout code
        uses: actions/checkout@v2

      # שלב 2: התקנת JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      # שלב 3: הורדת PMD והוצאתו
      - name: Download PMD
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases/6.58.0/pmd-bin-6.58.0.zip
          unzip pmd-bin-6.58.0.zip -d pmd
          export PMD_PATH=$(pwd)/pmd/pmd-bin-6.58.0/bin

      # שלב 4: ניתוח הקוד בעזרת PMD
      - name: Analyze code with PMD
        run: |
          $PMD_PATH/run.sh pmd \
          -d src \
          -R category/java/errorprone.xml \
          -f text > pmd-report.txt
          cat pmd-report.txt

      # שלב 5: הורדת Google Java Format
      - name: Download Google Java Format
        run: |
          curl -L -o google-java-format.jar https://github.com/google/google-java-format/releases/download/v1.17.0/google-java-format-1.17.0-all-deps.jar

      # שלב 6: תיקון הקוד בעזרת Google Java Format
      - name: Fix code with Google Java Format
        run: |
          for file in $(find src -name "*.java"); do
            java -jar google-java-format.jar --replace $file
          done

      # שלב 7: קומפילציה של הקוד המתוקן
      - name: Compile Java Code
        run: |
          javac src/*.java

      # שלב 8: ביצוע commit ושמירה של השינויים
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automatically fix Java issues"
          git push
